### PR TITLE
Add ability to parse signed number.

### PR DESCRIPTION
**Pull request by cheunghy**
Thanks for this fantastic color package! ;-)

It's legal to specify a signed number into css color expression.
So this commit add several ``[+-]?`` to add the ability.

### CODE REVIEW

**Comment by MoOx** [comment]
Can you add tests for this please ?

**Comment by cheunghy** [comment]
Sure.

**Comment by cheunghy** [comment]
Test added.

**Comment by ben-eb** [comment]
:+1:

**Pull request merged**
